export const REQUEST_USER = "REQUEST_USER";
export const SAVE_USER = "SAVE_USER";

export const GET_SESSION = "GET_SESSION";
export const GET_SESSION_ERROR = "GET_SESSION_ERROR";

export const SAVE_CHATMESSAGES = "SAVE_CHATMESSAGES";
export const REQUEST_CHATMESSAGES = "REQUEST_CHATMESSAGES";
